[package]
name = "label-edit"
version = "0.1.0"
description = "LabelEdit Desktop Application"
authors = ["LabelEdit Team"]
edition = "2021"

[lib]
name = "label_edit_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.1" }
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-log = "2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "blocking"] }
tokio = { version = "1", features = ["full"] }
